#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
Name     : rofi
Version  : 1.7.6
Release  : 5
URL      : https://github.com/davatorium/rofi/releases/download/1.7.6/rofi-1.7.6.tar.gz
Source0  : https://github.com/davatorium/rofi/releases/download/1.7.6/rofi-1.7.6.tar.gz
Summary  : Header files for rofi plugins
Group    : Development/Tools
License  : MIT
Requires: rofi-bin = %{version}-%{release}
Requires: rofi-data = %{version}-%{release}
Requires: rofi-license = %{version}-%{release}
Requires: rofi-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : flex
BuildRequires : libxkbcommon-dev
BuildRequires : pandoc
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(libstartup-notification-1.0)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : xcb-util-cursor-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center">
<a href="https://github.com/davatorium/rofi/issues"><img src="https://img.shields.io/github/issues/davatorium/rofi.svg"></a>
<a href="https://img.shields.io/github/forks/davatorium/rofi.svg"><img src="https://img.shields.io/github/forks/davatorium/rofi.svg"></a>
<a href="https://github.com/davatorium/rofi/stargazers"><img src="https://img.shields.io/github/stars/davatorium/rofi.svg"></a>
<a href="https://github.com/davatorium/rofi/releases"><img src="https://img.shields.io/github/downloads/davatorium/rofi/total.svg"></a>
<a href="https://repology.org/metapackage/rofi/versions"><img src="https://repology.org/badge/tiny-repos/rofi.svg"></a>
</p>

%package bin
Summary: bin components for the rofi package.
Group: Binaries
Requires: rofi-data = %{version}-%{release}
Requires: rofi-license = %{version}-%{release}

%description bin
bin components for the rofi package.


%package data
Summary: data components for the rofi package.
Group: Data

%description data
data components for the rofi package.


%package dev
Summary: dev components for the rofi package.
Group: Development
Requires: rofi-bin = %{version}-%{release}
Requires: rofi-data = %{version}-%{release}
Provides: rofi-devel = %{version}-%{release}
Requires: rofi = %{version}-%{release}

%description dev
dev components for the rofi package.


%package license
Summary: license components for the rofi package.
Group: Default

%description license
license components for the rofi package.


%package man
Summary: man components for the rofi package.
Group: Default

%description man
man components for the rofi package.


%prep
%setup -q -n rofi-1.7.6
cd %{_builddir}/rofi-1.7.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735580256
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735580256
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rofi
cp %{_builddir}/rofi-%{version}/COPYING %{buildroot}/usr/share/package-licenses/rofi/578d71749d002d6526f82c143c9dc1721fd6188d || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rofi
/usr/bin/rofi-sensible-terminal
/usr/bin/rofi-theme-selector

%files data
%defattr(-,root,root,-)
/usr/share/applications/rofi-theme-selector.desktop
/usr/share/applications/rofi.desktop
/usr/share/icons/hicolor/scalable/apps/rofi.svg
/usr/share/rofi/themes/Adapta-Nokto.rasi
/usr/share/rofi/themes/Arc-Dark.rasi
/usr/share/rofi/themes/Arc.rasi
/usr/share/rofi/themes/DarkBlue.rasi
/usr/share/rofi/themes/Indego.rasi
/usr/share/rofi/themes/Monokai.rasi
/usr/share/rofi/themes/Paper.rasi
/usr/share/rofi/themes/android_notification.rasi
/usr/share/rofi/themes/arthur.rasi
/usr/share/rofi/themes/blue.rasi
/usr/share/rofi/themes/c64.rasi
/usr/share/rofi/themes/dmenu.rasi
/usr/share/rofi/themes/docu.rasi
/usr/share/rofi/themes/fancy.rasi
/usr/share/rofi/themes/fancy2.rasi
/usr/share/rofi/themes/fullscreen-preview.rasi
/usr/share/rofi/themes/glue_pro_blue.rasi
/usr/share/rofi/themes/gruvbox-common.rasinc
/usr/share/rofi/themes/gruvbox-dark-hard.rasi
/usr/share/rofi/themes/gruvbox-dark-soft.rasi
/usr/share/rofi/themes/gruvbox-dark.rasi
/usr/share/rofi/themes/gruvbox-light-hard.rasi
/usr/share/rofi/themes/gruvbox-light-soft.rasi
/usr/share/rofi/themes/gruvbox-light.rasi
/usr/share/rofi/themes/iggy.jpg
/usr/share/rofi/themes/iggy.rasi
/usr/share/rofi/themes/lb.rasi
/usr/share/rofi/themes/material.rasi
/usr/share/rofi/themes/paper-float.rasi
/usr/share/rofi/themes/purple.rasi
/usr/share/rofi/themes/sidebar-v2.rasi
/usr/share/rofi/themes/sidebar.rasi
/usr/share/rofi/themes/solarized.rasi
/usr/share/rofi/themes/solarized_alternate.rasi

%files dev
%defattr(-,root,root,-)
/usr/include/rofi/helper.h
/usr/include/rofi/mode-private.h
/usr/include/rofi/mode.h
/usr/include/rofi/rofi-icon-fetcher.h
/usr/include/rofi/rofi-types.h
/usr/lib64/pkgconfig/rofi.pc

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rofi/578d71749d002d6526f82c143c9dc1721fd6188d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rofi-sensible-terminal.1
/usr/share/man/man1/rofi-theme-selector.1
/usr/share/man/man1/rofi.1
/usr/share/man/man5/rofi-debugging.5
/usr/share/man/man5/rofi-dmenu.5
/usr/share/man/man5/rofi-keys.5
/usr/share/man/man5/rofi-script.5
/usr/share/man/man5/rofi-theme.5
/usr/share/man/man5/rofi-thumbnails.5
